# This is a basic workflow to help you get started with Actions

name: Terraform Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (prod and non-prod)"
        required: true
        default: "non-prod"

jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    defaults:
      run:
        working-directory: ./env/${{ github.event.inputs.environment }}

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # 3. Configure AWS credentials (replace if GCP/Azure)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 4. Terraform Init
      - name: Terraform Init
        run: terraform init -input=false

      # 5. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false -var-file=envs/${{ github.event.inputs.environment }}.tfvars -out=tfplan

      # 6. Save plan as artifact
      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  apply:
    name: Terraform Apply ${{ github.event.inputs.environment }}
    needs: terraform
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Download tfplan
      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .

      # Terraform Apply (manual approval via GitHub Environments)
      - name: Terraform Apply
        run: terraform apply -input=false tfplan
